title: Xuanhe Zhang's Homepage
page-top-title: Xuanhe Zhang
top-section-bg-text: Be what you wanna be
home-subtitle: Xuanhe Zhang&infj;|&infj;张轩赫
copyright-text: '&copy; Xuanhe Zhang 2023-2025. All Rights Reserved.'